wechat:
  wcp:
    APP_ID:
    APPSECRET:
    MCH_ID:
    API_KEY:
    # 注册域名
    REGISTER_DOMAIN:
    # 支付授权目录
    JSAPI_PAYMENT_AUTH_DIR:
    # JS 安全域名
    JS_DOMAIN:
    # 网页授权域名
    WEB_AUTH_DOMAIN:
    # 证书路径
    APICLIENT_CERT:
    # 异步接收微信支付结果通知的回调地址，通知url必须为外网可访问的url，不能携带参数
    NOTIFY_URL:
    # 异步接收微信支付退款结果通知的回调地址，通知URL必须为外网可访问的url，不允许带参数，如果参数中传了notify_url，则商户平台上配置的回调地址将不会生效。
    NOTIFY_URL_REFUND:

spring:
  application:
    name: member-server
  redis:
    database: 0
    #单机版
    #    host: 127.0.0.1
    #    port: 6379
    #    password: 123456
    #      pool:
    #        max-idle: 100
    #        min-idle: 1
    #        max-active: 1000
    #        max-wait: -1
    #集群版
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    cluster:
      nodes:
        - 120.79.27.209:7000
        - 120.79.27.209:7001
        - 120.79.27.209:7002
        - 120.79.27.209:7003
        - 120.79.27.209:7004
        - 120.79.27.209:7005